version: 2.1

orbs:
  maven: circleci/maven@1.1.0

workflows:
  build:
    jobs:
      - maven/test:
          name: Run Tests
          command: 'compile resources:testResources compiler:testCompile surefire:test@atf-health'
  regression:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - maven/test:
          name: Nightly Regression
          command: 'compile resources:testResources compiler:testCompile surefire:test@regression'
  manual-regression:
    jobs:
      - hold:
          type: approval
      - maven/test:
          name: Manual Regression
          command: 'compile resources:testResources compiler:testCompile surefire:test@regression'
          requires:
            - hold