version: 2.1

orbs:
  maven: circleci/maven@1.1.0

workflows:
  build:
    jobs:
      - maven/test:
          name: Run ATF Unit Tests
          command: verify -P build
          test_results_path: core/target/surefire-reports
  run-system-integration-tests:
    jobs:
      - maven/test:
          name: Run System Integration Tests
          command: verify -P system-integration
          test_results_path: system-integration/target/failsafe-reports